M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu20.04.1} date 2025-01-23T22:26:57-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-23T22:26:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X83.312Y-71.628
X157.48Y-34.036
X158.75Y-96.5
M30
